#include "stdint.h"

#define CROSFP_REG_POWER_CTRL		0x00
#define CROSFP_REG_AMP_SNS_CTRL		0x01
#define CROSFP_REG_DAC_CTRL		0x02
#define CROSFP_REG_DAC_VOLUME		0x03
#define CROSFP_REG_SAI_CTRL_1		0x04
#define CROSFP_REG_SAI_CTRL_2		0x05
#define CROSFP_REG_SAI_PLACEMENT_1		0x06
#define CROSFP_REG_SAI_PLACEMENT_2		0x07
#define CROSFP_REG_SAI_PLACEMENT_3		0x08
#define CROSFP_REG_SAI_PLACEMENT_4		0x09
#define CROSFP_REG_SAI_PLACEMENT_5		0x0a
#define CROSFP_REG_SAI_PLACEMENT_6		0x0b
#define CROSFP_REG_BATTERY_V_OUT		0x0c
#define CROSFP_REG_LIMITER_CTRL_1		0x0d
#define CROSFP_REG_LIMITER_CTRL_2		0x0e
#define CROSFP_REG_LIMITER_CTRL_3		0x0f
#define CROSFP_REG_STATUS_1		0x10
#define CROSFP_REG_STATUS_2		0x11
#define CROSFP_REG_FAULT_CTRL		0x12
#define CROSFP_REG_PDM_CTRL		0x13
#define CROSFP_REG_MCLK_RATIO		0x14
#define CROSFP_REG_BOOST_CTRL_1		0x15
#define CROSFP_REG_BOOST_CTRL_2		0x16
#define CROSFP_REG_SOFT_RESET		0xff

/* POWER_CTRL */
#define CROSFP_POWER_APWDN_EN		BIT(7)
#define CROSFP_POWER_BSNS_PWDN		BIT(6)
#define CROSFP_POWER_VSNS_PWDN		BIT(5)
#define CROSFP_POWER_ISNS_PWDN		BIT(4)
#define CROSFP_POWER_BOOST_PWDN		BIT(3)
#define CROSFP_POWER_AMP_PWDN		BIT(2)
#define CROSFP_POWER_VBAT_ONLY		BIT(1)
#define CROSFP_POWER_SPWDN			BIT(0)

/* DAC_CTRL */
#define CROSFP_DAC_HV			BIT(7)
#define CROSFP_DAC_MUTE		BIT(6)
#define CROSFP_DAC_HPF			BIT(5)
#define CROSFP_DAC_LPM			BIT(4)
#define CROSFP_DAC_FS_MASK	0x7
#define CROSFP_DAC_FS_8000_12000	0x0
#define CROSFP_DAC_FS_16000_24000	0x1
#define CROSFP_DAC_FS_32000_48000	0x2
#define CROSFP_DAC_FS_64000_96000	0x3
#define CROSFP_DAC_FS_128000_192000	0x4

/* SAI_CTRL_1 */
#define CROSFP_SAI_CTRL_1_BCLK			BIT(6)
#define CROSFP_SAI_CTRL_1_TDM_BLCKS_MASK	(0x3 << 4)
#define CROSFP_SAI_CTRL_1_TDM_BLCKS_32		(0x0 << 4)
#define CROSFP_SAI_CTRL_1_TDM_BLCKS_48		(0x1 << 4)
#define CROSFP_SAI_CTRL_1_TDM_BLCKS_64		(0x2 << 4)
#define CROSFP_SAI_CTRL_1_FSYNC		BIT(3)
#define CROSFP_SAI_CTRL_1_LJ			BIT(2)
#define CROSFP_SAI_CTRL_1_TDM			BIT(1)
#define CROSFP_SAI_CTRL_1_PDM			BIT(0)

/* SAI_CTRL_2 */
#define CROSFP_SAI_CTRL_2_AUTO_SLOT		BIT(3)
#define CROSFP_SAI_CTRL_2_TDM_SLOT_MASK	0x7
#define CROSFP_SAI_CTRL_2_TDM_SLOT(x)		(x)